default: &default
  adapter: postgresql
  encoding: unicode
  host: <%=ENV['POSTGRES_HOST']%>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: fluge_development


test:
  <<: *default
  database: fluge_test

production:
  <<: *default
  host: localhost
  database: fluge_production
